### ISSUE TITLE
What's the source of this data?

### ISSUE THREAD

**Issue by vxsourcerer** [arjunswaj/elections#1]
First of all thanks for this data!
I am not a coder so couldn't figure it out? what's the source of this data? where did you got this from? 
I read the repository and learned its markdown but why is this an app? I mean app query result src test have you hosted this somewhere? 

I am not from stem background so the question may look noob to you sorry if it does I am just curious!

**Comment by arjunswaj** [comment]
Thanks for the comment. The source of this data is the website of [Election Commission of India](https://results.eci.gov.in/PcResultGenJune2024/index.htm).

This is not an app where I'm hosting any website. This is a [Haskell script](https://github.com/arjunswaj/elections/blob/main/src/Elections.hs#L55-L65) where webpage of every constituency is loaded and the results of the candidates are extracted out and are stored into an [aggregated CSV file](https://github.com/arjunswaj/elections/blob/main/election_results.csv).

This CSV is then [loaded into the Database](https://github.com/arjunswaj/elections/blob/main/queries/Queries.sql#L1-L22) and then SQL queries are [written and run on the database](https://github.com/arjunswaj/elections/tree/main/queries) to get the interesting insights into the data.

The full results of the above SQL queries run on the database is [stored here](https://github.com/arjunswaj/elections/tree/main/result).

**Comment by vxsourcerer** [comment]
Thank you Arjun! 
I will look into them thanks!
